<#
.SYNOPSIS
    Attack Simulation Instructions for IDS Demo
    For Thesis Defense - Windows PowerShell

.DESCRIPTION
    This script prints recommended attack simulation commands for testing the IDS.
    It does NOT execute attacks automatically - only provides instructions.
    Use these commands to generate attack traffic for the IDS to detect.

.NOTES
    Always ensure you have permission to test attacks on your network.
    These commands should only be used in controlled lab environments.
#>

Write-Host "=" * 80
Write-Host "IDS BACKEND - ATTACK SIMULATION INSTRUCTIONS"
Write-Host "Thesis Defense - Controlled Lab Environment Only"
Write-Host "=" * 80
Write-Host ""

Write-Host "IMPORTANT SAFETY NOTES:"
Write-Host "-" * 80
Write-Host "1. Only run these attacks in a controlled lab environment"
Write-Host "2. Ensure you have explicit permission to test on the target network"
Write-Host "3. Use a dedicated test VM or isolated network segment"
Write-Host "4. Do not run attacks against production systems or public networks"
Write-Host "5. This script only prints instructions - it does NOT execute attacks"
Write-Host ""

Write-Host "PREREQUISITES:"
Write-Host "-" * 80
Write-Host "Install required tools on Windows:"
Write-Host ""
Write-Host "1. Nmap (Port Scanner)"
Write-Host "   Download: https://nmap.org/download.html"
Write-Host "   Install: Windows installer"
Write-Host "   Verify: nmap --version"
Write-Host ""
Write-Host "2. hping3 (Packet Generator)"
Write-Host "   Download: http://www.hping.org/download.html"
Write-Host "   Install: Windows binary or use WSL/Cygwin"
Write-Host "   Verify: hping3 --version"
Write-Host ""
Write-Host "3. Hydra (Brute Force Tool)"
Write-Host "   Download: https://github.com/vanhauser-thc/thc-hydra"
Write-Host "   Install: Windows binary or use WSL/Cygwin"
Write-Host "   Verify: hydra -h"
Write-Host ""

Write-Host "ATTACK SIMULATION COMMANDS:"
Write-Host "=" * 80
Write-Host ""

Write-Host "1. PORT SCAN SIMULATION (Nmap)"
Write-Host "-" * 80
Write-Host "Purpose: Simulates reconnaissance phase of an attack"
Write-Host "Detection: IDS should detect as 'Port Scan' or 'Reconnaissance'"
Write-Host ""
Write-Host "Commands:"
Write-Host ""
Write-Host "  # TCP SYN scan (stealthy)"
Write-Host "  nmap -sS -p 1-1000 <target_ip>"
Write-Host ""
Write-Host "  # TCP Connect scan (noisier)"
Write-Host "  nmap -sT -p 1-1000 <target_ip>"
Write-Host ""
Write-Host "  # UDP scan"
Write-Host "  nmap -sU -p 1-1000 <target_ip>"
Write-Host ""
Write-Host "  # Aggressive scan (OS detection + version detection)"
Write-Host "  nmap -A -p 1-1000 <target_ip>"
Write-Host ""
Write-Host "  # Fast scan (top 100 ports)"
Write-Host "  nmap -F <target_ip>"
Write-Host ""
Write-Host "Example (test against localhost):"
Write-Host "  nmap -sS -p 1-1000 127.0.0.1"
Write-Host ""
Write-Host "Expected IDS Alert:"
Write-Host "  - Attack Type: Port Scan / Reconnaissance"
Write-Host "  - Severity: Medium to High"
Write-Host "  - Confidence: 0.7+"
Write-Host ""

Write-Host "2. DDOS SIMULATION (hping3)"
Write-Host "-" * 80
Write-Host "Purpose: Simulates denial of service attack"
Write-Host "Detection: IDS should detect as 'DDoS' or 'Flood'"
Write-Host ""
Write-Host "Commands:"
Write-Host ""
Write-Host "  # ICMP flood (ping flood)"
Write-Host "  hping3 -i u1000 <target_ip>"
Write-Host ""
Write-Host "  # TCP SYN flood"
Write-Host "  hping3 -S -i u1000 -p 80 <target_ip>"
Write-Host ""
Write-Host "  # UDP flood"
Write-Host "  hping3 --udp -i u1000 -p 53 <target_ip>"
Write-Host ""
Write-Host "  # Custom packet rate (1000 packets per second)"
Write-Host "  hping3 -i u1000 <target_ip>"
Write-Host ""
Write-Host "  # Slower rate for testing (100 packets per second)"
Write-Host "  hping3 -i u10000 <target_ip>"
Write-Host ""
Write-Host "Example (test against localhost):"
Write-Host "  hping3 -i u10000 127.0.0.1"
Write-Host ""
Write-Host "Expected IDS Alert:"
Write-Host "  - Attack Type: DDoS / Flood"
Write-Host "  - Severity: High to Critical"
Write-Host "  - Confidence: 0.8+"
Write-Host "  - High packet rate from single source"
Write-Host ""

Write-Host "3. BRUTE FORCE SIMULATION (Hydra)"
Write-Host "-" * 80
Write-Host "Purpose: Simulates credential guessing attack"
Write-Host "Detection: IDS should detect as 'Brute Force' or 'Authentication Attack'"
Write-Host ""
Write-Host "Commands:"
Write-Host ""
Write-Host "  # SSH brute force with username list"
Write-Host "  hydra -L usernames.txt -P passwords.txt ssh://<target_ip>"
Write-Host ""
Write-Host "  # SSH brute force with single username"
Write-Host "  hydra -l admin -P passwords.txt ssh://<target_ip>"
Write-Host ""
Write-Host "  # HTTP basic auth brute force"
Write-Host "  hydra -l admin -P passwords.txt <target_ip> http-get /"
Write-Host ""
Write-Host "  # FTP brute force"
Write-Host "  hydra -l admin -P passwords.txt ftp://<target_ip>"
Write-Host ""
Write-Host "Example (test against localhost SSH):"
Write-Host "  hydra -l admin -P passwords.txt ssh://127.0.0.1"
Write-Host ""
Write-Host "Create password list file (passwords.txt):"
Write-Host "  admin"
Write-Host "  password"
Write-Host "  123456"
Write-Host "  root"
Write-Host "  admin123"
Write-Host ""
Write-Host "Expected IDS Alert:"
Write-Host "  - Attack Type: Brute Force / Authentication Attack"
Write-Host "  - Severity: High"
Write-Host "  - Confidence: 0.7+"
Write-Host "  - Multiple failed authentication attempts"
Write-Host ""

Write-Host "4. MANUAL ATTACK GENERATION (PowerShell)"
Write-Host "-" * 80
Write-Host "Purpose: Generate simple attack traffic without external tools"
Write-Host "Detection: IDS should detect based on traffic patterns"
Write-Host ""
Write-Host "Commands:"
Write-Host ""
Write-Host "  # Generate rapid TCP connections (port scan simulation)"
Write-Host "  for ($i=1; $i -le 1000; $i++) {"
Write-Host "      Test-NetConnection -ComputerName <target_ip> -Port $i -WarningAction SilentlyContinue"
Write-Host "  }"
Write-Host ""
Write-Host "  # Generate ICMP packets (ping flood simulation)"
Write-Host "  for ($i=1; $i -le 1000; $i++) {"
Write-Host "      Test-NetConnection -ComputerName <target_ip> -WarningAction SilentlyContinue"
Write-Host "  }"
Write-Host ""
Write-Host "Example (test against localhost):"
Write-Host "  for ($i=1; $i -le 100; $i++) {"
Write-Host "      Test-NetConnection -ComputerName 127.0.0.1 -Port $i -WarningAction SilentlyContinue"
Write-Host "  }"
Write-Host ""

Write-Host "DEMO WORKFLOW:"
Write-Host "=" * 80
Write-Host ""
Write-Host "Step 1: Start the IDS backend"
Write-Host "  .\scripts\demo_full.ps1 -Interface <interface_name>"
Write-Host ""
Write-Host "Step 2: In a separate terminal, start WebSocket listener"
Write-Host "  wscat -c ws://localhost:8000/ws"
Write-Host ""
Write-Host "Step 3: Run one of the attack simulation commands above"
Write-Host "  Example: nmap -sS -p 1-1000 127.0.0.1"
Write-Host ""
Write-Host "Step 4: Observe real-time alerts in WebSocket terminal"
Write-Host ""
Write-Host "Step 5: Check alerts via API"
Write-Host "  curl.exe http://localhost:8000/api/alerts/ -H 'X-API-Key: <your-key>'"
Write-Host ""
Write-Host "Step 6: Stop the sniffer"
Write-Host "  curl.exe -X POST http://localhost:8000/api/sniffer/stop -H 'X-API-Key: <your-key>'"
Write-Host ""

Write-Host "EXPECTED SCREENSHOTS FOR THESIS DEFENSE:"
Write-Host "=" * 80
Write-Host ""
Write-Host "1. Attack command execution (e.g., nmap output)"
Write-Host "2. Real-time WebSocket alert stream showing attack detection"
Write-Host "3. API response showing captured alerts with attack details"
Write-Host "4. Alert details showing:"
Write-Host "   - Attack type (e.g., 'Port Scan')"
Write-Host "   - Severity level (e.g., 'High')"
Write-Host "   - Confidence score (e.g., 0.85)"
Write-Host "   - Source IP and destination IP"
Write-Host "   - Timestamp"
Write-Host "5. Dashboard view (if frontend is available)"
Write-Host ""

Write-Host "CLEANUP AFTER DEMO:"
Write-Host "=" * 80
Write-Host ""
Write-Host "1. Stop the sniffer (if not already stopped)"
Write-Host "2. Stop the backend server"
Write-Host "3. Stop Docker containers: docker-compose down"
Write-Host "4. Review and clear test alerts from database if needed"
Write-Host ""

Write-Host "DISCLAIMER:"
Write-Host "=" * 80
Write-Host "This script is for educational and thesis demonstration purposes only."
Write-Host "Always obtain proper authorization before conducting security testing."
Write-Host "Unauthorized network scanning or attacks are illegal."
Write-Host ""
